services:
  website:
    image: nginx:alpine
    volumes:
      - hugo_content:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.middlewares.website-ratelimit.ratelimit.average: "20"
        traefik.http.routers.website.entrypoints: "websecure"
        traefik.http.routers.website.middlewares: "website-ratelimit"
        traefik.http.routers.website.rule: "Host(`duedraghialmicrofono.com`) && !Method(`POST`)"
        traefik.http.routers.website.tls.certresolver: "myresolver"
        traefik.http.services.website.loadbalancer.server.port: "80"

volumes:
  hugo_content:
    name: duedraghi-site_hugo_content

