services:
  website:
    image: ghcr.io/emiliopalmerini/duedraghialmicrofono.com/website:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      labels:
        traefik.enable: "true"
        traefik.http.middlewares.website-ratelimit.ratelimit.average: "20"
        traefik.http.routers.website.entrypoints: "websecure"
        traefik.http.routers.website.middlewares: "website-ratelimit"
        traefik.http.routers.website.rule: "Host(`duedraghialmicrofono.com`) && !Method(`POST`)"
        traefik.http.routers.website.tls.certresolver: "myresolver"
        traefik.http.services.website.loadbalancer.server.port: "80"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true

