name: Build & Deploy

on:
  push:
    branches:
      - "main"

permissions:
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: emiliopalmerini/duedraghialmicrofono.com
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true
      
      - name: Build website with Hugo
        run: hugo --minify
      
      - name: Create nginx config
        run: |
          cat > nginx.conf << 'EOF'
          server {
              listen       80;
              server_name  duedraghialmicrofono.com;
              root   /usr/share/nginx/html;

              gzip on;
              gzip_vary on;
              gzip_min_length 10240;
              gzip_proxied expired no-cache no-store private auth;
              gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/xml application/javascript;
              gzip_disable "MSIE [1-6]\.";

              location / {
                  index  index.html index.htm;
                  try_files $uri $uri/ =404;
                  expires 7d;
                  add_header Cache-Control "public, max-age=604800";
              }

              error_page   500 502 503 504  /50x.html;
              location = /50x.html {
                  root   /usr/share/nginx/html;
                  internal;
              }
          }
          EOF
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/website:latest
            ghcr.io/${{ github.repository }}/website:${{ github.sha }}
      
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: duedraghialmicrofono.com
          username: deploy
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          script: |
            # Aggiorna il service Docker per usare la nuova immagine
            docker service update --image ghcr.io/${{ github.repository }}/website:${{ github.sha }} duedraghi-site_website

